const fs = require('fs');
const path = require('path');

const envContent = `/* ============================================
   District Gaming Zone — Autogenerated Environment Keys
   ============================================ */

window.firebaseConfigEnv = {
  apiKey: "${process.env.FIREBASE_API_KEY || 'YOUR_API_KEY'}",
  authDomain: "${process.env.FIREBASE_AUTH_DOMAIN || 'YOUR_AUTH_DOMAIN'}",
  projectId: "${process.env.FIREBASE_PROJECT_ID || 'YOUR_PROJECT_ID'}",
  storageBucket: "${process.env.FIREBASE_STORAGE_BUCKET || 'YOUR_STORAGE_BUCKET'}",
  messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER_ID || 'YOUR_MESSAGING_SENDER_ID'}",
  appId: "${process.env.FIREBASE_APP_ID || 'YOUR_APP_ID'}",
  measurementId: "${process.env.FIREBASE_MEASUREMENT_ID || 'YOUR_MEASUREMENT_ID'}"
};
`;

const destPath = path.join(__dirname, 'js', 'env.js');
fs.mkdirSync(path.dirname(destPath), { recursive: true });
fs.writeFileSync(destPath, envContent);
console.log("🚀 Environment variables injected successfully into js/env.js!");
