const fs = require('fs');
const path = require('path');

const clean = (val) => (val || "").trim().replace(/\r?\n|\r/g, "");

const envContent = `/* ============================================
   District Gaming Zone — Autogenerated Environment Keys
   ============================================ */

window.firebaseConfigEnv = {
  apiKey: "${clean(process.env.FIREBASE_API_KEY) || 'YOUR_API_KEY'}",
  authDomain: "${clean(process.env.FIREBASE_AUTH_DOMAIN) || 'YOUR_AUTH_DOMAIN'}",
  projectId: "${clean(process.env.FIREBASE_PROJECT_ID) || 'YOUR_PROJECT_ID'}",
  storageBucket: "${clean(process.env.FIREBASE_STORAGE_BUCKET) || 'YOUR_STORAGE_BUCKET'}",
  messagingSenderId: "${clean(process.env.FIREBASE_MESSAGING_SENDER_ID) || 'YOUR_MESSAGING_SENDER_ID'}",
  appId: "${clean(process.env.FIREBASE_APP_ID) || 'YOUR_APP_ID'}",
  measurementId: "${clean(process.env.FIREBASE_MEASUREMENT_ID) || 'YOUR_MEASUREMENT_ID'}"
};
`;

const destPath = path.join(__dirname, 'js', 'env.js');
fs.mkdirSync(path.dirname(destPath), { recursive: true });
fs.writeFileSync(destPath, envContent);
console.log("🚀 Environment variables injected successfully into js/env.js!");
